---

- name: Create site <-> CID map
  set_fact:
    location_mapping: {
      # dpc to dpc
      "DAL006 vSphere 6.5 INAP Manage Hosting": "Superior Integrated Solutions - 194116",
      "SIS - NYJ - Production": "Superior Integrated Solutions - 194116",
      "RAF-DAL-DRAAS": "Radiologic Associates of Fredericksburg - 21937",
      "RAF-NYJ-PROD": "Radiologic Associates of Fredericksburg - 21937",
      "AAP-CHG1": "American Academy of Pediatrics - 188292",
      "AAP-PHX01": "American Academy of Pediatrics - 188292",
      "DAL006 (Dallas)": "Velocitor - 20621",
      "ACS (Atlanta)": "Velocitor - 20621",
      "Falcone CHI": "Falcone - 193525",
      "Falcone PHX": "Falcone - 193525",
      # dpc to shared
      "APTA": "American Physical Therapy Association - 191900",
      "D and A Service LLC": "D&A Services - 186423",
      "DAL DPC": "P.E.O. International - 191569",
      "Gmount": "Glass Mountain Holdings LLC - 193421",
      # offsite to dpc
      "CHI-DRaaS": "AquaFinance - 188955",
      "USSRVDRDPC": "US Services - 193605",
      # offsite to shared
      "tpvcntr": "Total Power Limited - 193893 - Shared CHI ZVM",
      "dlusa": "Deutsche Leasing USA - 191349 - Shared CHI ZVM",
      "Wells": "Spancrete - 193567 - Shared CHI ZVM",
      "lsg_NJ": "Lightstone Group - 189646 - Shared CHI ZVM",
      "MLRT": "McElroy Truck Lines - 191969 - Shared CHI ZVM",
      "Gibney NYC Office VM7.15": "Gibney, Anthony & Flaherty, LLP - 191966 - Shared CHI ZVM",
      "ORNL Federal Credit Union": "ORNL Federal Credit Union - 18273 - Shared CHI ZVM",
      "Singlehop CHI3": "Shared CHI ZVM",
      "GAL Site": "Canada Ltd - 194012 - Shared CHI ZVM"
    }

- name: Get Zerto Alarms
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/monitoring/alerts"
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ api_token }}"
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Filter alarms with type VPG0010
  set_fact:
    filtered_alarms: "{{ login.json | json_query('[?type==`VPG0010`]') }}"

- name: Set threshold time (24 hours ago)
  set_fact:
    threshold_time: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime((ansible_date_time.epoch | int) - (24 * 60 * 60)) }}"

- name: Filter alarms older than 24 hours
  set_fact:
    old_alarms: >-
      {{
        filtered_alarms | selectattr('collectionTime', 'lt', threshold_time) | list
      }}

- name: Format filtered alarms into a single string
  set_fact:
    formatted_alarms: |
      {%- for alarm in old_alarms %}
      Issue appeared on: {{ alarm.collectionTime }}
      Severity: {{ alarm.severity }}
      Description: {{ alarm.description }}
      Zerto Analytics: https://analytics.zerto.com/dashboard
      Client: {{ location_mapping[alarm.site.name] | default('Unknown') }}
      Site Name | Zorg Identifier: {{ alarm.site.name }} | {{ alarm.affectedZorgs }}

      {% endfor %}

- name: Print formatted alarms
  debug:
    var: formatted_alarms

- name: Write results to file
  copy:
    content: "{{ formatted_alarms }}"
    dest: "~/zerto_alarms-{{ ansible_date_time.date }}.txt"
  delegate_to: 172.16.101.183


- name: Sending an e-mail to ticket queue
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: '{{ gmail_smtp_user }}'
    password: '{{ gmail_smtp_pw }}'
    to: <ms-support@inap.com>
    subject: Daily Zerto RPO Breaches
    body: '{{ formatted_alarms }}'