---

- name: Get Zerto Token
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/auth/token"
    method: POST
    headers:
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body:
    - [ user, '{{ username }}' ]
    - [ password, '{{ password }}' ]
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Print Token
  debug:
    var: login.stdout