---

- name: Get Zerto Alarms
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/monitoring/alerts"
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ token }}"
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Filter alarms with type VPG0010
  set_fact:
    filtered_alarms: "{{ login.json | json_query('[?type==`VPG0010`]') }}"

- name: Print filtered alarms
  debug:
    msg:
      - 'Issue appeared on: {{ item.collectionTime }}'
      - 'Alarm ID: {{ item.type }}'
      - 'Severity: {{ item.severity }}'
      - 'Description: {{ item.description }}'
      - 'Locaiton: {{ item.site }}'
  loop: '{{ filtered_alarms }}'
  register: file_content

- name: write results to file
  copy:
    content: '{{ file_content }}'
    dest: '~/alarms.txt'
  delegate_to: 172.16.101.183