---

- name: Get Zerto Alarms
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/monitoring/alerts"
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ token }}"
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Filter alarms with type VPG0010
  set_fact:
    filtered_alarms: "{{ login.json | json_query('[?type==`VPG0010`]') }}"

- name: Format filtered alarms into a single string
  set_fact:
    formatted_alarms: |
      {%- for alarm in filtered_alarms %}
      Client ID: TODO make array of site to CIDs
      Issue appeared on: {{ alarm.collectionTime }}
      URL: idk how to do this yet
      Severity: {{ alarm.severity }}
      Description: {{ alarm.description }}
      Location: {{ alarm.site.name, alarm.affectedZorgs }}

      {% endfor %}

- name: Print formatted alarms
  debug:
    var: formatted_alarms

- name: Write results to file
  copy:
    content: "{{ formatted_alarms }}"
    dest: "~/alarms.txt"
  delegate_to: 172.16.101.183
