---

- name: Create zerto API Key
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/monitoring/alerts"
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ token }}"
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Filter alarms with type VPG0010
  set_fact:
    filtered_alarms: "{{ login.json | json_query('alerts[?type==`VPG0010`]') }}"

- name: Print filtered alarms
  debug:
    var: filtered_alarms