---

- name: Get Zerto Token
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/auth/token"
    method: POST
    headers:
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body:
      username: '{{ awx_zerto_user }}'
      password: '{{ awx_zerto_pw }}'
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Print Token
  debug:
    var: login.json.token