---

- name: Get Zerto Alarms
  ansible.builtin.uri:
    url: "https://analytics.api.zerto.com/v2/auth/token"
    method: POST
    headers:
      Accept: application/json
      Content-Type: application/json
    user: '{{ username }}'
    password: '{{ password }}'
    validate_certs: false
    force_basic_auth: yes
    return_content: true
  register: login

- name: Filter alarms with type VPG0010
  debug:
    var: login.stdout